markernum: 0
# rotation and translate from frame to marker
#0.1848+0.11684+0.05974
measured_translation: [0.38138, 0, -0.162]
measured_rot: [-1, 0, 0, 0, -1, 0, 0, 0, 1]
frame: "/base"

#For display purposes only
squaredims: [0.07, 0.04, 0.02]

